EMBDER_CONFIG:
  credentials: "..."
  scope: "GIGACHAT_API_CORP"
  verify_ssl_certs: False
  timeout: 1200

DB_CONFIG:
  collection_name:  "moex"
  client_url: "http://localhost:6333"
  payload_key: "data"

PROMPT_CONFIG:
  query_prompt: "Используй контекст предыдущих сообщений и текущее сообщение для переформулировки одного запроса для поисковой системы по семантической близости, запрос касается законодательства, поэтому должен быть формальным и хорошо обобщать запрос пользователя. Ничего лишнего не пиши, нужен запрос в систему
	               Текущее сообщение:
                 {current_message}
                 Переформулированный запрос:"
  query_prompt_with_history: "Используй контекст предыдущих сообщений и текущее сообщение для переформулировки одного запроса для поисковой системы по семантической близости, запрос касается законодательства, поэтому должен быть формальным и хорошо обобщать запрос пользователя. Ничего лишнего не пиши, нужен запрос в систему
                              Контекст предыдущих сообщений и ответов:
                              {history}
                              Текущее сообщение:
                              {current_message}
                              Переформулированный запрос:"
  response_prompt: "Используй следующий контекст для подробного и законченного ответа на вопрос пользователя. Если из контекста никак не следует ответ на вопрос пользователя (оригинальный запрос), то сообщи об этом. Вопрос пользователя может быть очень конкретным, постарайся обобщить и найти в контексте ответ. Отвечай на русском языке.
                    Контекст из базы данных:
                    {retrieved_chunks}
                    Оригинальный запрос:
                    {original_query}
                    Переформулированный запрос:
                    {formulated_query}
                    Ответ:"
  num_queries: 1
  max_context_length: 6000

LLM_CONFIG:
  credentials: "..."
  model: "GigaChat-Pro"
  scope: "GIGACHAT_API_CORP"
  profanity_check: "false"
  verify_ssl_certs: False
  timeout: 1200 